apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  labels:
    name: mdex-1s5m
  name: mdex-1s5m
spec:
  ports:
  - name: mdex
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: cas
    port: 8006
    protocol: TCP
    targetPort: 8006
  - name: lb-mdex
    port: 17000
    protocol: TCP
    targetPort: 17000
  - name: authoring-mdex
    port: 17002
    protocol: TCP
    targetPort: 17002
  - name: log-mdex
    port: 17010
    protocol: TCP
    targetPort: 17010
  selector:
    name: mdex-1s5m
  sessionAffinity: None
  type: ClusterIP
